import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  base: "./",
  cacheDir: "node_modules/.vite",
  server: {
    host: true,
    hmr: {
      overlay: false,
    },
    watch: {
      usePolling: true,
    },
    proxy: {
      "/api": {
        target: "http://localhost:11000",
        changeOrigin: true,
      },
    },
  },
  optimizeDeps: {
    include: [
      "react",
      "react-dom",
      "react-router-dom",
      "@emotion/react",
      "@emotion/styled",
      "@mui/material",
      "@mui/icons-material/AccessTime",
      "@mui/icons-material/AccessTimeFilled",
      "@mui/icons-material/AccessTimeOutlined",
      "@mui/icons-material/AccountBalance",
      "@mui/icons-material/Add",
      "@mui/icons-material/AddAlert",
      "@mui/icons-material/AddCircleOutline",
      "@mui/icons-material/AddOutlined",
      "@mui/icons-material/AdminPanelSettings",
      "@mui/icons-material/Analytics",
      "@mui/icons-material/AnalyticsOutlined",
      "@mui/icons-material/Announcement",
      "@mui/icons-material/ApartmentOutlined",
      "@mui/icons-material/Apps",
      "@mui/icons-material/ArrowBack",
      "@mui/icons-material/ArrowBackIos",
      "@mui/icons-material/ArrowBackOutlined",
      "@mui/icons-material/ArrowDownward",
      "@mui/icons-material/ArrowForward",
      "@mui/icons-material/ArrowForwardIos",
      "@mui/icons-material/ArrowLeft",
      "@mui/icons-material/ArrowUpward",
      "@mui/icons-material/ArticleOutlined",
      "@mui/icons-material/Assessment",
      "@mui/icons-material/Assignment",
      "@mui/icons-material/AssignmentLate",
      "@mui/icons-material/AssignmentOutlined",
      "@mui/icons-material/AssignmentTurnedIn",
      "@mui/icons-material/AttachMoney",
      "@mui/icons-material/AutoAwesome",
      "@mui/icons-material/AutoAwesomeMosaic",
      "@mui/icons-material/AutoAwesomeOutlined",
      "@mui/icons-material/AutoMode",
      "@mui/icons-material/AutoStoriesOutlined",
      "@mui/icons-material/Autorenew",
      "@mui/icons-material/BackupTable",
      "@mui/icons-material/Badge",
      "@mui/icons-material/BadgeOutlined",
      "@mui/icons-material/BarChart",
      "@mui/icons-material/BarChartOutlined",
      "@mui/icons-material/BeachAccess",
      "@mui/icons-material/Block",
      "@mui/icons-material/BlockOutlined",
      "@mui/icons-material/BugReport",
      "@mui/icons-material/Business",
      "@mui/icons-material/BusinessCenter",
      "@mui/icons-material/BusinessOutlined",
      "@mui/icons-material/Calculate",
      "@mui/icons-material/CalendarMonth",
      "@mui/icons-material/CalendarMonthOutlined",
      "@mui/icons-material/CalendarToday",
      "@mui/icons-material/CalendarTodayOutlined",
      "@mui/icons-material/Campaign",
      "@mui/icons-material/Cancel",
      "@mui/icons-material/CancelOutlined",
      "@mui/icons-material/Category",
      "@mui/icons-material/Check",
      "@mui/icons-material/CheckCircle",
      "@mui/icons-material/CheckCircleOutline",
      "@mui/icons-material/CheckCircleOutlineOutlined",
      "@mui/icons-material/CheckCircleRounded",
      "@mui/icons-material/ChevronLeft",
      "@mui/icons-material/ChevronRight",
      "@mui/icons-material/Circle",
      "@mui/icons-material/CircleNotifications",
      "@mui/icons-material/Clear",
      "@mui/icons-material/Close",
      "@mui/icons-material/Cloud",
      "@mui/icons-material/CloudSync",
      "@mui/icons-material/CloudUpload",
      "@mui/icons-material/CoffeeMaker",
      "@mui/icons-material/CompareArrows",
      "@mui/icons-material/Computer",
      "@mui/icons-material/ContactPhone",
      "@mui/icons-material/CorporateFare",
      "@mui/icons-material/CurrencyExchange",
      "@mui/icons-material/DarkMode",
      "@mui/icons-material/Dashboard",
      "@mui/icons-material/DashboardOutlined",
      "@mui/icons-material/DataObject",
      "@mui/icons-material/DataUsageOutlined",
      "@mui/icons-material/DateRange",
      "@mui/icons-material/Delete",
      "@mui/icons-material/DeleteOutline",
      "@mui/icons-material/Description",
      "@mui/icons-material/DescriptionOutlined",
      "@mui/icons-material/DesignServices",
      "@mui/icons-material/Difference",
      "@mui/icons-material/Dining",
      "@mui/icons-material/Diversity1",
      "@mui/icons-material/DocumentScanner",
      "@mui/icons-material/Download",
      "@mui/icons-material/Edit",
      "@mui/icons-material/EditCalendar",
      "@mui/icons-material/EditNoteOutlined",
      "@mui/icons-material/EditOutlined",
      "@mui/icons-material/Email",
      "@mui/icons-material/Engineering",
      "@mui/icons-material/Error",
      "@mui/icons-material/ErrorOutline",
      "@mui/icons-material/Event",
      "@mui/icons-material/EventAvailable",
      "@mui/icons-material/EventAvailableOutlined",
      "@mui/icons-material/EventBusy",
      "@mui/icons-material/EventNote",
      "@mui/icons-material/ExitToApp",
      "@mui/icons-material/ExpandLess",
      "@mui/icons-material/ExpandMore",
      "@mui/icons-material/FamilyRestroom",
      "@mui/icons-material/FiberManualRecord",
      "@mui/icons-material/FileDownload",
      "@mui/icons-material/FileDownloadOutlined",
      "@mui/icons-material/FilterList",
      "@mui/icons-material/FilterListOff",
      "@mui/icons-material/FindInPage",
      "@mui/icons-material/Fingerprint",
      "@mui/icons-material/Folder",
      "@mui/icons-material/FolderOpen",
      "@mui/icons-material/FreeBreakfast",
      "@mui/icons-material/Gavel",
      "@mui/icons-material/GridOn",
      "@mui/icons-material/GridView",
      "@mui/icons-material/Group",
      "@mui/icons-material/GroupOutlined",
      "@mui/icons-material/Groups",
      "@mui/icons-material/GroupsOutlined",
      "@mui/icons-material/HealthAndSafety",
      "@mui/icons-material/Help",
      "@mui/icons-material/HelpOutline",
      "@mui/icons-material/HighlightOff",
      "@mui/icons-material/History",
      "@mui/icons-material/Home",
      "@mui/icons-material/HomeWork",
      "@mui/icons-material/HourglassEmpty",
      "@mui/icons-material/HowToReg",
      "@mui/icons-material/Inbox",
      "@mui/icons-material/Info",
      "@mui/icons-material/InfoOutlined",
      "@mui/icons-material/InsertDriveFile",
      "@mui/icons-material/Insights",
      "@mui/icons-material/Inventory",
      "@mui/icons-material/Inventory2",
      "@mui/icons-material/KeyboardArrowDown",
      "@mui/icons-material/KeyboardArrowLeft",
      "@mui/icons-material/KeyboardArrowRight",
      "@mui/icons-material/KeyboardArrowUp",
      "@mui/icons-material/LaptopMac",
      "@mui/icons-material/LibraryBooks",
      "@mui/icons-material/LightMode",
      "@mui/icons-material/Lightbulb",
      "@mui/icons-material/Link",
      "@mui/icons-material/LinkOff",
      "@mui/icons-material/ListAlt",
      "@mui/icons-material/LocalAtm",
      "@mui/icons-material/LocalOffer",
      "@mui/icons-material/LocalShipping",
      "@mui/icons-material/Lock",
      "@mui/icons-material/LockOutlined",
      "@mui/icons-material/LockReset",
      "@mui/icons-material/Logout",
      "@mui/icons-material/Mail",
      "@mui/icons-material/MailOutline",
      "@mui/icons-material/MeetingRoom",
      "@mui/icons-material/Menu",
      "@mui/icons-material/MergeType",
      "@mui/icons-material/MonetizationOn",
      "@mui/icons-material/MoreHoriz",
      "@mui/icons-material/MoreTime",
      "@mui/icons-material/MoreVert",
      "@mui/icons-material/MoveToInbox",
      "@mui/icons-material/NewReleases",
      "@mui/icons-material/Notes",
      "@mui/icons-material/NotificationImportant",
      "@mui/icons-material/Notifications",
      "@mui/icons-material/NotificationsActive",
      "@mui/icons-material/NotificationsOutlined",
      "@mui/icons-material/Numbers",
      "@mui/icons-material/Outbox",
      "@mui/icons-material/Pending",
      "@mui/icons-material/PendingActions",
      "@mui/icons-material/People",
      "@mui/icons-material/PeopleAlt",
      "@mui/icons-material/PeopleAltOutlined",
      "@mui/icons-material/PeopleOutline",
      "@mui/icons-material/Percent",
      "@mui/icons-material/Person",
      "@mui/icons-material/PersonAdd",
      "@mui/icons-material/PersonAddAlt",
      "@mui/icons-material/PersonAddOutlined",
      "@mui/icons-material/PersonOutlineOutlined",
      "@mui/icons-material/PersonOutlined",
      "@mui/icons-material/PersonSearch",
      "@mui/icons-material/Phone",
      "@mui/icons-material/PictureAsPdf",
      "@mui/icons-material/PieChart",
      "@mui/icons-material/PlayArrow",
      "@mui/icons-material/PlayCircleOutline",
      "@mui/icons-material/PlaylistAdd",
      "@mui/icons-material/PointOfSale",
      "@mui/icons-material/PostAdd",
      "@mui/icons-material/Print",
      "@mui/icons-material/QrCodeScanner",
      "@mui/icons-material/RadioButtonUnchecked",
      "@mui/icons-material/RateReview",
      "@mui/icons-material/Receipt",
      "@mui/icons-material/ReceiptLong",
      "@mui/icons-material/Refresh",
      "@mui/icons-material/RemoveCircle",
      "@mui/icons-material/ReportProblem",
      "@mui/icons-material/ReportProblemOutlined",
      "@mui/icons-material/RequestQuote",
      "@mui/icons-material/RestartAlt",
      "@mui/icons-material/Restaurant",
      "@mui/icons-material/RocketLaunchOutlined",
      "@mui/icons-material/Room",
      "@mui/icons-material/Save",
      "@mui/icons-material/Schedule",
      "@mui/icons-material/School",
      "@mui/icons-material/Search",
      "@mui/icons-material/SearchOff",
      "@mui/icons-material/Send",
      "@mui/icons-material/Settings",
      "@mui/icons-material/SettingsSuggest",
      "@mui/icons-material/ShoppingBag",
      "@mui/icons-material/ShoppingCart",
      "@mui/icons-material/ShowChart",
      "@mui/icons-material/SignalWifi1Bar",
      "@mui/icons-material/SignalWifi2Bar",
      "@mui/icons-material/SignalWifi3Bar",
      "@mui/icons-material/SignalWifi4Bar",
      "@mui/icons-material/SignalWifiOff",
      "@mui/icons-material/SmartToy",
      "@mui/icons-material/SortOutlined",
      "@mui/icons-material/Speed",
      "@mui/icons-material/Star",
      "@mui/icons-material/Stars",
      "@mui/icons-material/Storage",
      "@mui/icons-material/Store",
      "@mui/icons-material/Storefront",
      "@mui/icons-material/Summarize",
      "@mui/icons-material/SupervisorAccount",
      "@mui/icons-material/SwapHoriz",
      "@mui/icons-material/SwapVert",
      "@mui/icons-material/TaskAlt",
      "@mui/icons-material/Timer",
      "@mui/icons-material/TransferWithinAStation",
      "@mui/icons-material/TrendingUp",
      "@mui/icons-material/Tune",
      "@mui/icons-material/Update",
      "@mui/icons-material/UploadFile",
      "@mui/icons-material/ViewList",
      "@mui/icons-material/ViewModule",
      "@mui/icons-material/Visibility",
      "@mui/icons-material/VisibilityOff",
      "@mui/icons-material/VisibilityOutlined",
      "@mui/icons-material/VpnKey",
      "@mui/icons-material/Warehouse",
      "@mui/icons-material/Warning",
      "@mui/icons-material/WarningAmber",
      "@mui/icons-material/Work",
      "@mui/icons-material/WorkOutline",
      "@mui/icons-material/WorkspacePremium",
      "@mui/system",
      "@mui/x-data-grid",
      "@mui/x-date-pickers",
      "@tanstack/react-query",
      "dayjs",
      "date-fns",
      "clsx",
      "chart.js",
      "react-chartjs-2",
      "lucide-react",
      "file-saver",
      "exceljs",
      "xlsx",
      "jspdf",
      "jspdf-autotable",
      "papaparse",
      "pdfjs-dist",
      "yup",
      "react-hook-form",
      "@hookform/resolvers",
    ],
    exclude: ["ollama"],
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("node_modules")) {
            if (id.includes("@directus/sdk")) return "directus";
            if (
              id.includes("@mui") ||
              id.includes("@emotion") ||
              id.includes("@tanstack") ||
              id.includes("react") ||
              id.includes("react-dom") ||
              id.includes("react-router-dom")
            ) {
              return "vendor";
            }
          }
        },
      },
    },
    sourcemap: false,
    minify: "esbuild",
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "@resoluciones": path.resolve(__dirname, "./src/apps/resoluciones"),
    },
  },
});
