import type { Traslado } from '../components/TrasladoCard';



export const MOCK_TRASLADOS: Traslado[] = [
  {
    id: 1,
    fecha: '2025-10-03',
    bodega_Origen: 'B001',
    nombre_Origen: 'Bodega Central',
    bodega_Destino: 'B002',
    nombre_Destino: 'Sucursal Norte',
    unidades: 120,
  },
  {
    id: 2,
    fecha: '2025-10-03',
    bodega_Origen: 'B003',
    nombre_Origen: 'Sucursal Sur',
    bodega_Destino: 'B002',
    nombre_Destino: 'Sucursal Norte',
    unidades: 80,
  },
  {
    id: 3,
    fecha: '2025-10-06',
    bodega_Origen: 'B004',
    nombre_Origen: 'Éxito Cali',
    bodega_Destino: 'B005',
    nombre_Destino: 'Universidades',
    unidades: 30,
  },
  {
    id: 4,
    fecha: '2025-10-06',
    bodega_Origen: 'B004',
    nombre_Origen: 'Éxito Cali',
    bodega_Destino: 'B006',
    nombre_Destino: 'Pasto Centro',
    unidades: 45,
  },
  {
    id: 5,
    fecha: '2025-10-07',
    bodega_Origen: 'B007',
    nombre_Origen: 'Carulla Medellín',
    bodega_Destino: 'B005',
    nombre_Destino: 'Universidades',
    unidades: 25,
  },
  {
    id: 6,
    fecha: '2025-10-07',
    bodega_Origen: 'B008',
    nombre_Origen: 'Jumbo Bogotá',
    bodega_Destino: 'B009',
    nombre_Destino: 'Bogotá Occidente',
    unidades: 90,
  },
  {
    id: 7,
    fecha: '2025-10-08',
    bodega_Origen: 'B004',
    nombre_Origen: 'Éxito Cali',
    bodega_Destino: 'B010',
    nombre_Destino: 'Cali Sur',
    unidades: 60,
  },
  {
    id: 8,
    fecha: '2025-10-08',
    bodega_Origen: 'B011',
    nombre_Origen: 'Alkosto Pereira',
    bodega_Destino: 'B005',
    nombre_Destino: 'Universidades',
    unidades: 35,
  },
  {
    id: 9,
    fecha: '2025-10-09',
    bodega_Origen: 'B007',
    nombre_Origen: 'Carulla Medellín',
    bodega_Destino: 'B012',
    nombre_Destino: 'Medellín Norte',
    unidades: 70,
  },
  {
    id: 10,
    fecha: '2025-10-09',
    bodega_Origen: 'B004',
    nombre_Origen: 'Éxito Cali',
    bodega_Destino: 'B005',
    nombre_Destino: 'Universidades',
    unidades: 50,
  },
  {
    id: 11,
    fecha: '2025-10-10',
    bodega_Origen: 'B013',
    nombre_Origen: 'Éxito Barranquilla',
    bodega_Destino: 'B014',
    nombre_Destino: 'Barranquilla Centro',
    unidades: 55,
  },
  {
    id: 12,
    fecha: '2025-10-10',
    bodega_Origen: 'B001',
    nombre_Origen: 'Bodega Central',
    bodega_Destino: 'B015',
    nombre_Destino: 'Cartagena',
    unidades: 100,
  },
];

   
export const Listas_Bodegas = [
   'Bodega Central',
  'Sucursal Norte',
  'Sucursal Sur',
  'Éxito Cali',
  'Universidades',
  'Pasto Centro',
  'Carulla Medellín',
  'Jumbo Bogotá',
  'Bogotá Occidente',
  'Cali Sur',
  'Alkosto Pereira',
  'Medellín Norte',
  'Éxito Barranquilla',
  'Barranquilla Centro',
  'Cartagena',
];